modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/nanite/Literal-Sky-Block/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "literalskyblock"
version = "${version}"
displayName = "Literal Sky Block"
authors = "LatvianModder"
description = '''
This mod adds blocks that simulate sky
'''

[[dependencies.literalskyblock]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.literalskyblock]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"